Worlds:
- 'resource'
- 'resource_nether'
- 'resource_the_end'
Blocks:
  DIRT: 50
  STONE: 150
  GRASS_BLOCK: 75
  GRAVEL: 75
  OBSIDIAN: 200
  COBBLESTONE: 200
  NETHERRACK: 50
  END_STONE: 300
  COAL_ORE: 300
  IRON_ORE: 300
  GOLD_ORE: 300
  DIAMOND_ORE: 300
  LAPIS_ORE: 300
  REDSTONE_ORE: 300
  NETHER_QUARTZ_ORE: 300
UpperLimit:
  Normal: 9
  Slime: 12
  Guardian: 18
  Pigman: 10